// Message d'invitation au Portail gérance (email / SMS / WhatsApp), partagé par le portail et l'app de gestion
// text : texte simple (SMS, email simple) ; wa : WhatsApp (*gras*) ; html : invitation mise en forme à coller dans un email
const SIGN = 'LuxInterventions — ARES INVEST S.A.\n📞 +352 691 423 943 · ✉️ info@luxinterventions.com\n🌐 luxinterventions.com';
const ORANGE = '#E8723A';
const L = {
  fr: { subject: 'Bienvenue chez LuxInterventions — votre accès au portail', hello: 'Bonjour', welcome: 'Bienvenue chez LuxInterventions !', thanks: 'Merci de nous avoir choisis. Nous sommes très heureux de travailler avec vous.', intro: 'Voici votre accès personnel au portail des gérances : vos demandes d’intervention 24 h/24, les photos, le suivi en direct et les rapports, au même endroit.', step: 'Choisissez votre mot de passe', stepHint: 'Ouvrez le lien et choisissez votre mot de passe une seule fois. Ensuite : votre email + ce mot de passe, sur tous vos appareils.', btn: 'Choisir mon mot de passe', valid: 'Lien personnel, valable 14 jours, utilisable une seule fois.', bye: 'À très bientôt,', team: 'L’équipe LuxInterventions' },
  de: { subject: 'Willkommen bei LuxInterventions — Ihr Zugang zum Portal', hello: 'Hallo', welcome: 'Willkommen bei LuxInterventions!', thanks: 'Danke, dass Sie sich für uns entschieden haben. Wir freuen uns sehr auf die Zusammenarbeit.', intro: 'Hier ist Ihr persönlicher Zugang zum Verwaltungsportal: Ihre Einsatzanfragen rund um die Uhr, Fotos, Live-Verfolgung und Berichte an einem Ort.', step: 'Wählen Sie Ihr Passwort', stepHint: 'Öffnen Sie den Link und wählen Sie Ihr Passwort ein einziges Mal. Danach: Ihre E-Mail + dieses Passwort, auf allen Geräten.', btn: 'Mein Passwort wählen', valid: 'Persönlicher Link, 14 Tage gültig, nur einmal verwendbar.', bye: 'Bis bald,', team: 'Ihr LuxInterventions-Team' },
  en: { subject: 'Welcome to LuxInterventions — your portal access', hello: 'Hello', welcome: 'Welcome to LuxInterventions!', thanks: 'Thank you for choosing us. We are very happy to work with you.', intro: 'Here is your personal access to the property managers’ portal: your job requests 24/7, photos, live tracking and reports, all in one place.', step: 'Choose your password', stepHint: 'Open the link and choose your password just once. After that: your email + this password, on all your devices.', btn: 'Choose my password', valid: 'Personal link, valid for 14 days, can be used only once.', bye: 'See you soon,', team: 'The LuxInterventions team' },
  it: { subject: 'Benvenuti in LuxInterventions — il vostro accesso al portale', hello: 'Buongiorno', welcome: 'Benvenuti in LuxInterventions!', thanks: 'Grazie di averci scelto. Siamo molto felici di lavorare con voi.', intro: 'Ecco il vostro accesso personale al portale delle gérances: le richieste di intervento 24 ore su 24, le foto, il seguito in diretta e i rapporti, tutto in un unico posto.', step: 'Scegliete la vostra password', stepHint: 'Aprite il link e scegliete la password una sola volta. Poi: la vostra email + questa password, su tutti i vostri dispositivi.', btn: 'Scegliere la mia password', valid: 'Link personale, valido 14 giorni, utilizzabile una sola volta.', bye: 'A prestissimo,', team: 'Il team LuxInterventions' },
  pt: { subject: 'Bem-vindo à LuxInterventions — o seu acesso ao portal', hello: 'Olá', welcome: 'Bem-vindo à LuxInterventions!', thanks: 'Obrigado por nos ter escolhido. Estamos muito felizes por trabalhar consigo.', intro: 'Aqui está o seu acesso pessoal ao portal das gestoras: os seus pedidos de intervenção 24 h/24, fotos, acompanhamento em direto e relatórios, num só lugar.', step: 'Escolha a sua palavra-passe', stepHint: 'Abra o link e escolha a sua palavra-passe uma única vez. Depois: o seu email + esta palavra-passe, em todos os seus aparelhos.', btn: 'Escolher a minha palavra-passe', valid: 'Link pessoal, válido 14 dias, utilizável uma só vez.', bye: 'Até muito em breve,', team: 'A equipa LuxInterventions' },
  es: { subject: 'Bienvenido a LuxInterventions — tu acceso al portal', hello: 'Hola', welcome: '¡Bienvenido a LuxInterventions!', thanks: 'Gracias por elegirnos. Estamos muy contentos de trabajar contigo.', intro: 'Aquí tienes tu acceso personal al portal de administradoras: tus solicitudes de intervención 24 h, fotos, seguimiento en directo e informes, en un solo lugar.', step: 'Elige tu contraseña', stepHint: 'Abre el enlace y elige tu contraseña una sola vez. Después: tu email + esta contraseña, en todos tus dispositivos.', btn: 'Elegir mi contraseña', valid: 'Enlace personal, válido 14 días, de un solo uso.', bye: '¡Hasta muy pronto!', team: 'El equipo LuxInterventions' },
};
const escH = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const mk = (t) => ({
  subject: t.subject,
  text: (n, l) => `${t.hello} ${n},\n\n🎉 ${t.welcome}\n${t.thanks}\n\n${t.intro}\n\n🔑 ${t.step.toUpperCase()} :\n${l}\n\n${t.stepHint}\n⏳ ${t.valid}\n\n${t.bye}\n${t.team}\n\n${SIGN}`,
  wa: (n, l) => `${t.hello} ${n},\n\n🎉 *${t.welcome}*\n${t.thanks}\n\n${t.intro}\n\n🔑 *${t.step}* 👇\n${l}\n\n${t.stepHint}\n⏳ _${t.valid}_\n\n${t.bye}\n*${t.team}*\n\n${SIGN}`,
  html: (n, l) => `<div style="font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.55;color:#1f1f1f;max-width:560px">
<p style="margin:0 0 6px;text-align:center"><img src="https://luxinterventions.com/assets/email-4elements.jpg" alt="Terre · Eau · Feu · Air — LuxInterventions" width="260" style="display:block;width:260px;max-width:100%;height:auto;margin:0 auto"></p>
<p style="margin:0 0 18px;text-align:center;font-family:Georgia,'Times New Roman',serif;font-style:italic;font-size:26px;letter-spacing:1px"><span style="color:#1f1f1f">LUX</span><span style="color:${ORANGE}">INTERVENTIONS</span></p>
<p style="margin:0 0 10px">${escH(t.hello)} ${escH(n)},</p>
<p style="margin:0 0 6px;font-size:20px;font-weight:bold;color:${ORANGE}">🎉 ${escH(t.welcome)}</p>
<p style="margin:0 0 14px"><b>${escH(t.thanks)}</b></p>
<p style="margin:0 0 18px">${escH(t.intro)}</p>
<p style="margin:0 0 8px;font-size:17px;font-weight:bold;color:${ORANGE}">🔑 ${escH(t.step)}</p>
<p style="margin:0 0 16px"><a href="${escH(l)}" style="display:inline-block;background:${ORANGE};color:#ffffff;text-decoration:none;font-weight:bold;padding:13px 24px;border-radius:12px">${escH(t.btn)} →</a></p>
<p style="margin:0 0 6px">${escH(t.stepHint)}</p>
<p style="margin:0 0 18px;font-size:13px;color:#6b6b6b">⏳ ${escH(t.valid)}<br><a href="${escH(l)}" style="color:${ORANGE};word-break:break-all">${escH(l)}</a></p>
<p style="margin:0">${escH(t.bye)}<br><b>${escH(t.team)}</b></p>
<p style="margin:16px 0 0;padding-top:12px;border-top:2px solid ${ORANGE};font-size:13px;color:#555">LuxInterventions — ARES INVEST S.A.<br>📞 +352 691 423 943 · ✉️ <a href="mailto:info@luxinterventions.com" style="color:${ORANGE}">info@luxinterventions.com</a> · 🌐 <a href="https://luxinterventions.com" style="color:${ORANGE}">luxinterventions.com</a></p>
</div>`,
});
export const PTL_INVITE = Object.fromEntries(Object.entries(L).map(([k, t]) => [k, mk(t)]));
